apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-recommender  
  template:
    metadata:
      labels:
        app: playlist-recommender
    spec:
      containers:
      - name: playlist-recommender
        image: vitorlucio/tp2-server:latest
        ports:
        - containerPort: 32216
      - name: playlist-rules-generator
        image: vitorlucio/tp2-rules-generator:latest
