apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: <user>-playlist-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer