apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: matheussilva
  name: project2-pv-matheussilva
  labels:
    type: local
spec:
  resources:
      requests:
        storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
